apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ parameters.serviceName | dump }}
  description: {{ parameters.description | dump }}
  annotations:
    github.com/project-slug: {{ parameters.repoUrl | parseRepoUrl 'owner' }}/{{ parameters.repoUrl | parseRepoUrl 'repo' }}
    backstage.io/techdocs-ref: url:./
spec:
  type: service # Ou 'website' si c'est pour un site
  lifecycle: experimental # Ou production, development, etc.
  owner: ${{ parameters.owner }}
  system: boaz-study # Attache automatiquement au système BOAZ-STUDY