apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ values.serviceName | dump }}
  description: {{ values.description | dump }}
  annotations:
    github.com/project-slug: '{{ values.repoUrl | parseRepoUrl "owner" }}/{{ values.repoUrl | parseRepoUrl "repo" }}'
    backstage.io/techdocs-ref: url:./
spec:
  type: service
  lifecycle: experimental
  owner: {{ values.owner | dump }}
  system: boaz-study
