apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ parameters.serviceName | dump }}
  description: ${{ values.description | dump }}
  annotations:
    github.com/project-slug: '${{ parameters.repoUrl | parseRepoUrl "owner" }}/${{ parameters.repoUrl | parseRepoUrl "repo" }}'
    backstage.io/techdocs-ref: url:./
spec:
  type: service
  lifecycle: experimental
  owner: ${{ parameters.owner | dump }}
  system: boaz-study
